command! ReTest call refactoring#test()
command! RenameLocalViriable call refactoring#renameLocalVariable()
command! InlineTemp call refactoring#inlineTemp()
command! ExtractConstant call refactoring#extractConstant()
command! ExtractMethod call refactoring#extractMethod()
